#
# Module manifest for module 'Posh-Spotify'
#
# Generated by: New-Guy
#
# Generated on: 06/24/2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Posh-Spotify.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# ID used to uniquely identify this module
GUID = '142c6804-0361-4fc9-9e30-c9e86de5d311'

# Author of this module
Author = 'New-Guy'

# Company or vendor of this module
CompanyName = 'New-Guy.com'

# Copyright statement for this module
Copyright = '(c) 2016 New-Guy.com. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This module contains powershell wrappers to leverage the Spotify API functions described here https://developer.spotify.com/web-api/'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'Amd64'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @(
    'Model\Formats\Album.Format.ps1xml',
    'Model\Formats\Artist.Format.ps1xml',
    'Model\Formats\AuthenticationToken.Format.ps1xml',
    'Model\Formats\Copyright.Format.ps1xml',
    'Model\Formats\ExternalId.Format.ps1xml',
    'Model\Formats\ExternalUrl.Format.ps1xml',
    'Model\Formats\FollowerInfo.Format.ps1xml',
    'Model\Formats\ImageInfo.Format.ps1xml',
    'Model\Formats\PagingInfo.Format.ps1xml',
    'Model\Formats\Player.Format.ps1xml',
    'Model\Formats\Playlist.Format.ps1xml',
    'Model\Formats\Track.Format.ps1xml',
    'Model\Formats\User.Format.ps1xml'
)

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
# FunctionsToExport = @()

# Cmdlets to export from this module
# CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module
# AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
               'Functions\Album.ps1',
               'Functions\Artist.ps1',
               'Functions\DefaultSession.ps1',
               'Functions\Environment.ps1',
               'Functions\Initialize-SpotifyAuthorizationCodeFlow.ps1',
               'Functions\Invoke-SpotifyRequest.ps1',
               'Functions\PagingInfo.ps1',
               'Functions\Player.ps1',
               'Functions\Playlist.ps1',
               'Functions\Track.ps1',
               'Model\Formats\Album.Format.ps1xml',
               'Model\Formats\Artist.Format.ps1xml',
               'Model\Formats\AuthenticationToken.Format.ps1xml',
               'Model\Formats\ExternalId.Format.ps1xml',
               'Model\Formats\ExternalUrl.Format.ps1xml',
               'Model\Formats\FollowerInfo.Format.ps1xml',
               'Model\Formats\ImageInfo.Format.ps1xml',
               'Model\Formats\PagingInfo.Format.ps1xml',
               'Model\Formats\Playlist.Format.ps1xml',
               'Model\Formats\Playlist.Format.ps1xml',
               'Model\Formats\Track.Format.ps1xml',
               'Model\Formats\User.Format.ps1xml',
               'Model\Album.cs',
               'Model\Artist.cs',
               'Model\AuthenticationToken.cs',
               'Model\Copyright.cs',
               'Model\ExternalId.cs',
               'Model\ExternalUrl.cs',
               'Model\FollowerInfo.cs',
               'Model\ImageInfo.cs',
               'Model\Import-ObjectModel.ps1',
               'Model\PagingInfo.cs',
               'Model\Playler.cs',
               'Model\Playlist.cs',
               'Model\Track.cs',
               'Model\User.cs',
               'SpotifyEnvironmentInfo\SpotifyEnvironmentInfo.ps1',
               'Variables\ModuleVariables.ps1',
               'Posh-Spotify.psd1',
               'Posh-Spotify.psm1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/The-New-Guy/Posh-Spotify'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

